# .github/workflows/publish.yaml

name: Build and publish a bundle

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Checkout the repository with full history
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # fetch all branches, not just default

      - name: Checkout submodule branch 'publish'
        run: |
          cd publish
          git fetch origin
          git checkout publish
          git pull origin publish

      - name: Set Git user identity
        run: |
          git config --global user.email "lilliputten@gmail.com"
          git config --global user.name "lilliputten"

      - name: Get info
        run: |
          cd publish
          git status

      - name: Setup pnpm using the official action
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js with caching for pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.confirmModulesPurge=false

      - name: Build the project
        run: pnpm build

      - name: Update build
        run: ./.utils/publish-update.sh

      - name: Publish build
        run: ./.utils/github-publish.sh

      - name: Publish with tags
        run: ./.utils/publish-push-with-tags.sh
